### ISSUE TITLE
Multiple create ec2 

### ISSUE THREAD

**Issue by kanlicali** [digitalresonance/EC2-Cloud-Miner#1]
hello, how can I start multiple different instances

**Comment by DigitalResonance** [comment]
Hi kanlicali, since we are using the launch configuration of Autoscaling groups, we can only have one primary instance type. 

Usually I start multiple stacks from cloudformation using this template.
eg : 
 cloudformation stack A  : mining xmr using 4 x m5.xlarge 
 cloudformation stack A  : mining bcn using 8 x c5.xlarge 
...

If you want to start different instance types within the same cloudformation stack, you will need to modify the cloudformation template to use AWS::EC2::SpotFleet instead of AWS::AutoScaling::LaunchConfiguration and AWS::AutoScaling::AutoScalingGroup

Please let me know if you have any other questions.

**Comment by kanlicali** [comment]
Hello there,
Thank you very much for your reply.
But what I plan to do is,
Miner settings are fixed,
Xmr will be selected, mail will be entered.
But I will choose more than one machine.

![cloudformation](https://user-images.githubusercontent.com/13773668/36937274-d7b3ac66-1f21-11e8-88ba-e307a65af4b8.jpg)

https://imgur.com/a/BLoty

**Comment by kanlicali** [comment]
I also think that I will add t2 unlimited option
