### ISSUE TITLE
Are we allowed to use AWS credits for mining?

### ISSUE THREAD

**Issue by shree-crypto** [digitalresonance/EC2-Cloud-Miner#4]
Were you allowed to use the AWS credits for mining? How much credit did you use and for how long ? Were you given any type of warning?

**Comment by xavier-thomas** [comment]
Sorry, I've just seen this issue.
I had around $500 of credits that I used to mine back in 2018. Since I had a small fleet (4 - 8) of miners running I ran out of credits in around 5 - 7 days.

The instances were not terminated nor did I receive any type of warning.

Things could be very different now as it's been around 5 years since I did this.
